### ISSUE TITLE
Very slow on a large set of nested sortable items.

### ISSUE THREAD

**Issue by mrmachine** [alsoicode/django-admin-sortable#162]
We were seeing render times of ~3 minutes when trying to render the nested page with a couple thousand items grouped into a couple hundred parent items.

Profiling revealed that the vast majority of the time was in the app dirs template loader. When we enabled the cached template loader, render time sped up by ~6x, but it still takes ~30 seconds and again the vast majority of the time is now on template `render()` calls.

I suspect it's because of the way the sort view first renders its main template, which calls a template tag which renders another template, which calls another template tag in a loop (thousands of times) which renders another template.

It might be faster if we could somehow remove the render() call inside the loop across all items?

**Comment by alsoicode** [comment]
Pull requests are always welcome :)

I'm currently working on a very large project at work and won't have time to look into this issue for quite a while.

**Comment by alsoicode** [comment]
@mrmachine Are you still seeing slow render times on the latest version of admin sortable?

**Comment by mrmachine** [comment]
@alsoicode we're stuck on a Django 1.6 so I don't think the latest version will work for us. Can you point me to a commit that you think improved the situation in the latest version? Perhaps I can apply the fix to an the old version we are using.

**Comment by alsoicode** [comment]
@mrmachine 2.0.18 is probably the latest version you can use with Django 1.6

**Comment by mrmachine** [comment]
Was there a particular change in more recent versions that improved performance that I could look at to backport?

We previously worked around this issue by adding many filters to the change list page e.g. "change sort order for items beginning with A..., B..., C..., etc." but now the number of items has grown and even these filters are causing timeouts and massive load average on our servers.

**Comment by alsoicode** [comment]
@mrmachine No. I'm afraid that with the dynamic rendering of the object, the extra processing is always going to slow you down with very large datasets. It might be possible to do an extremely specific implementation of the sort list that only calls the model field you need to display vs figuring out what to render.

**Comment by mrmachine** [comment]
I've implemented some improvements in a fork against 2.0.18 here:

https://github.com/ixc/django-admin-sortable/commit/08ebc3198e49e7968178734f81bc2c3b1000af63

I have not yet tried to rebase this onto `master` (as we are stuck on 2.0.18).

@alsoicode do these changes look worthwhile to persue in a PR against master?

**Comment by mrmachine** [comment]
Rebased (but untested) and PR opened against master at https://github.com/alsoicode/django-admin-sortable/pull/185
