### ISSUE TITLE
Sortable many to many field

### ISSUE THREAD

**Issue by treyhunner** [alsoicode/django-admin-sortable#17]
I don't see a sortable many-to-many field in the documentation.

I am already using this project for some foreign key fields and have a need for a sortable many-to-many field.

Would this be a desirable feature for this project?

**Comment by orzel** [comment]
Why is it closed ? Is this done ? There's no reference to any git revision or tag or software release ... ?

**Comment by alsoicode** [comment]
It was never implemented, and given that the OP didn't have any additional feedback, the issue was closed.

**Comment by orzel** [comment]
Not sure what "OP" means.
Anyway, sortable M2M are really useful for the common case where people want to select a subset of something, and be able to sort it. It's available in other similar django sort applications, and i guess it can be somehow done already with django-admin-sortable, but it's not straightforward (nor documented).

**Comment by alsoicode** [comment]
OP -> Original Poster

Feel free to offer a pull request. You can already sort subsets of a model, just not a M2M.

**Comment by izhukov1992** [comment]
I used it for Many-to-Many in the next way and it works:
`
#models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from adminsortable.models import Sortable
from adminsortable.fields import SortableForeignKey

from django.contrib import admin
from adminsortable.admin import (
    SortableAdmin, SortableTabularInline
)
from .models import (
    Image, Gallery, GalleryImageRelation
)

class Image(models.Model):
    """Model of Image entity
    """

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    file = models.ImageField(
        verbose_name=_('File')
    )

    def __str__(self):
        return self.file.name


class Gallery(models.Model):
    """Model of Gallery entity
    """

    class Meta:
        verbose_name = _('Gallery')
        verbose_name_plural = _('Galleries')

    name = models.CharField(
        max_length=255, verbose_name=_('Name')
    )
    images = models.ManyToManyField(
        Image,
        through_fields=('gallery', 'image'),
        through='GalleryImageRelation',
        verbose_name=_('Images')
    )

    def __str__(self):
        return self.name


class GalleryImageRelation(Sortable):
    """Many to many relation model of Gallery and Image entities
    """

    class Meta(Sortable.Meta):
        verbose_name = _('Gallery image')
        verbose_name_plural = _('Gallery images')

    image = SortableForeignKey(
        Image, verbose_name=_("Image")
    )
    gallery = models.ForeignKey(
        Gallery, verbose_name=_("Gallery")
    )

    def __str__(self):
        return self.image.file.name

#admin.py
class GalleryImageRelationInlineAdmin(SortableTabularInline):

    model = GalleryImageRelation
    extra = 1


class GalleryAdmin(SortableAdmin):

    inlines = (
        GalleryImageRelationInlineAdmin,
    )

admin.site.register(Gallery, GalleryAdmin)
`

Hope it will help in the future.

**Comment by alsoicode** [comment]
@izhukov1992 Please feel free to create a pull request with updates to the readme and I'll take a look.

**Comment by alsoicode** [comment]
@izhukov1992 Did you want to create a pull request with your many-to-many implementation?

**Comment by izhukov1992** [comment]
@alsoicode Yes, please leave this ticket opened. I'm a bit busy now, but I will try to find a code where I used  it and update usage info asap.

**Comment by alsoicode** [comment]
@izhukov1992 If you'd like to add your M2M implementation, please create a pull request, otherwise I'd like to close this issue.

**Comment by ruslankrivoshein** [comment]
@izhukov1992, ну что же Вы?

**Comment by izhukov1992** [comment]
@ruslankrivoshein вот только недавно нашёл исходники проекта, где это использовал. Постараюсь добавить инфу.

**Comment by blag** [comment]
Now that #232 is merged, I think this long-standing issue can be closed. Sortable many to many models are possible with this project, they just have to be made explicit.

However, for anybody in the future who stumbles across this comment, here is a current summary of other projects that I am aware of, and how they differ from this project:

The [django-sortedm2m project](https://github.com/jazzband/django-sortedm2m) implements a drop-in, sortable replacement for Django's built-in ManyToManyField if users are looking for that. Note that the user interface for sorting models does not make it easy to reorder only a subset of models:

![django-sortedm2m user interface for reordering selected options](https://camo.githubusercontent.com/46588827d8ba32523aaa9fc04cfd76a2d955ad39/687474703a2f2f692e696d6775722e636f6d2f486a4957374d492e6a7067)

The [django-admin-sortable2](https://github.com/jrief/django-admin-sortable2) project also allows users to implement a sorted many-to-many relation, but it does not seem to support a sortable model with an unsortable parent model. Additionally, all of its [criticisms against "other" sortable model implementations](https://github.com/jrief/django-admin-sortable2#why-should-you-use-it) are no longer valid.
