### ISSUE TITLE
Usage outside of admin page?

### ISSUE THREAD

**Issue by peterhriser** [alsoicode/django-admin-sortable#170]
Would it be possible to make this functionality appear outside of the admin page?

**Comment by alsoicode** [comment]
If your user is authenticated, the url patterns for adminsortable should be available.

**Comment by peterhriser** [comment]
Do you have an example of this?

**Comment by alsoicode** [comment]
If you look at: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/admin.py#L89

You'll see an example of the pattern. Basically, you just need to POST an object, containing the ordering indexes of the objects you want to order:

`{'indexes': [2, 1, 3]}`

to the sorting URL, which identifies the model via it's content type id.

**Comment by alsoicode** [comment]
@peterhriser Were you able to follow the admin url for sorting?

**Comment by peterhriser** [comment]
@alsoicode No I am not following exactly how I am supposed to make it so. I basically just need this drag and drop ability in reordering to appear on a template.

**Comment by alsoicode** [comment]
Np. You can implement any drag-and-drop library you want, such as native HTML5 drag-and-drop or something like [dragula](https://github.com/bevacqua/dragula)

On drop, you need to post the order of the objects in the format of: `{'indexes': [2, 1, 3]}` to the admin sorting URL that corresponds to your model object's content type id. The order index values should come from the order the objects are in the DOM.

To get the order index values, you could use jQuery or just plain query selectors to get a reference to the DOM node containing the objects you're ordering. Just loop over them and add the index of the loop to the array. See: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/static/adminsortable/js/admin.sortable.js for a jQuery UI based example.

The admin url is dynamic, depending on your model meta's `app_label`, `model_name` and the content type id, so you can reverse them in templates if necessary. The url `name` is comprised of

```
admin:[app_label]_[model_name]_sort
```

which expects a keyword arg of: `model_type_id` that is your model's content type id.

**Comment by alsoicode** [comment]
Closing for now, but will re-open if you still need help.
