### ISSUE TITLE
Is there a readthedocs link for this project?

### ISSUE THREAD

**Issue by Flimm** [alsoicode/django-admin-sortable#171]
This repo has a `docs/` directory, which usually indicates that the docs are hosted on readthedocs.org. But the README has no link to this documentation. Is there a link for this somewhere?

**Comment by alsoicode** [comment]
@Flimm Unfortunately no, but the readme is pretty extensive.

**Comment by Flimm** [comment]
Hmm. So is this link out-of-date, then, or of a fork? https://readthedocs.org/projects/django-admin-sortable/

**Comment by alsoicode** [comment]
The link is out of date.
