### ISSUE TITLE
Django rest framework integration

### ISSUE THREAD

**Issue by Arlefreak** [alsoicode/django-admin-sortable#172]
Is there a way to use the order on a vieset from django res?

**Comment by alsoicode** [comment]
If you're authenticated, you can access the URL(s) to re-order objects. All that's expected is that the POST request is sent via Ajax.

See: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/admin.py#L237 for the view that does the sorting.

See: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/admin.py#L88 for the URL pattern.

**Comment by Arlefreak** [comment]
Oh sorry but I meant for order that the django rest framework query set returns on a list viewset, currently I have a SortableForeignKey, so the view return first all the objects with order 0 instead of ordered by the parent.

**Comment by alsoicode** [comment]
I'm not understanding what you're asking...

**Comment by Arlefreak** [comment]
Ok so I have this api endpoint: 

`https://api.ellugar.co/portfolio/projectsImages/?project__id=&project__slug=&imgType=mni`

Which returns a list of images related to a Project object which I have like this:

``` python
class Project(SortableMixin):
    order = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    name = models.CharField(max_length=140)
    class Meta:
        ordering = ['order', ]

class Image(SortableMixin):
    order = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    project = SortableForeignKey('Project')
    class Meta:
        ordering = ['order', ]

```

If I enter the admin/changeorder I get order as it should be:

<img width="689" alt="screen shot 2017-05-19 at 2 31 00 pm" src="https://cloud.githubusercontent.com/assets/1025751/26263903/3f0f434e-3ca0-11e7-98dc-3f6f34ac6ada.png">

And in the admin/list view I get all the 0-order first and instead of the order based on the Parent object, the same result on the api endpoint.


<img width="946" alt="screen shot 2017-05-19 at 2 37 00 pm" src="https://cloud.githubusercontent.com/assets/1025751/26264028/ceb65938-3ca0-11e7-9ca5-291d11ce462f.png">

Sorry if it was confusing

**Comment by alsoicode** [comment]
Right, because `Image` instances are ordered relative to their parent. Since there is only one image per Project in this case, they all have the same order, 0. What are you expecting/trying to do?

**Comment by Arlefreak** [comment]
A way to return the images of the first project and then all the images from the second project.

**Comment by alsoicode** [comment]
In one query? If so, I would filter the list of projects by id, then iterate over the images for each project and return them as a list. Is that what you're wanting? Keep in mind that your Image models are sorted for each project, so without the context of the project they belong to, the other is going to have little meaning.

**Comment by Arlefreak** [comment]
Yes that's what I wanted to accomplish, I think I misunderstood the functionality of the SortableForeignKey
