### ISSUE TITLE
http://127.0.0.1:8000/login/

### ISSUE THREAD

**Issue by Deepakmpi28** [alsoicode/django-admin-sortable#173]
Request Method:	GET
Request URL:	http://127.0.0.1:8000/login/
Django Version:	1.11.2
Exception Type:	TemplateSyntaxError
Exception Value:	
'crispy_form_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
static
staticfiles
tz

**Comment by alsoicode** [comment]
What does this have to do with Django Admin Sortable?
