### ISSUE TITLE
'Library' object has no attribute 'assignment_tag' (Django 2.0)

### ISSUE THREAD

**Issue by shacker** [alsoicode/django-admin-sortable#176]
Setting up a fresh project in Django 2.0 beta, using default setup instructions, Django admin throws crashing error:

`'Library' object has no attribute 'assignment_tag'`

Django 2 [release notes](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0) say:

"The assignment_tag helper is removed."

Django 1.11 docs [say](https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#assignment-tags):

"Deprecated since version 1.9:
simple_tag can now store results in a template variable and should be used instead."

**Comment by shacker** [comment]
Looks like a quick fix: Change:

`adminsortable/templatetags/django_template_additions.py:79`

to:

`@register.simple_tag`

**Comment by alsoicode** [comment]
Ok, I will take a look.

**Comment by alsoicode** [comment]
I'm running into significant issues upgrading from 1.11 to 2. I'll work through them as quickly as I can.

**Comment by shacker** [comment]
Maybe easier to do a fresh virtualenv for a Django 2 test?

If helpful, I can do a PR for this and you can pip install my version from the PR.

**Comment by shacker** [comment]
PR: 
https://github.com/alsoicode/django-admin-sortable/pull/177

**Comment by alsoicode** [comment]
@shacker These changes are now included in the 2.1.2 release.
