### ISSUE TITLE
CSRF Token stored in Session not Cookie

### ISSUE THREAD

**Issue by cburger** [alsoicode/django-admin-sortable#178]
Some penetration tests flags storing the CSRF token in a cookie as a security vulnerability. [Django 1.11 now support storing the CSRF token in the session](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-CSRF_USE_SESSIONS).

When setting `CSRF_USE_SESSIONS = True`, the CSRF fails when changing sorting. 

To fix this issue the token should be injected into `jquery.django-csrf.html` and it should use this token instead of the cookie.

**Comment by alsoicode** [comment]
Hi @cburger I always welcome pull requests if you have an idea of how to address the issue.

**Comment by cburger** [comment]
Hi @alsoicode, I made a PR which solves the issue. I have not yet looked at test coverage though.

**Comment by alsoicode** [comment]
Changes are now part of 2.1.2 release.
