### ISSUE TITLE
`extra_filters` can only pass kwargs to `filter`, but not args

### ISSUE THREAD

**Issue by Flimm** [alsoicode/django-admin-sortable#184]
I would like to be able to do something like this:

```python
object.get_next(extra_filters=[Q(field1=True) | Q(field2=True)])
```

However, if I do, I get this error:

```
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

Looking at the code, it looks like `extra_filters` is passed as keyword arguments to Django ORM's `filter` method, but there doesn't seem to be a way to pass positional arguments.

Maybe, `extra_filters` should be replaced with two arguments: `extra_filters_kwargs`, and `extra_filters_args`.

**Comment by alsoicode** [comment]
Evening @Flimm. Sorry for the slow response; I've been swamped lately. I'll try to take a look into this as soon as possible for you. Pull Requests are always welcome.

**Comment by alsoicode** [comment]
@Flimm My sincere apologies for taking so incredibly long to get back to your request. I've added the ability to pass positional arguments to the get next/previous filters in the develop branch for you to test out.

Now you can do an override of `get_next()` as such:

from django.db import models

```
class YourModel(SortableMixin):
    title = models.CharField(max_length=100)
    field1 = models.BooleanField(default=False)
    field2 = modes.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_next(self):
        return super(YourModel, self).get_next(
            filter_args=[models.Q(field1=True) | models.Q(field2=True)])
```

This is working for me as expected in the Sample Project within the repo. You'll see a similar override on the "Project" model. If you shell in and select an object, then call `.get_next()`, you should see the object you expect.

Please let me know if this will work for you, and if so, I'll get a new release out to PyPi.

**Comment by alsoicode** [comment]
@Flimm This functionality has been included in 2.1.9, which is available on PyPi.

**Comment by Flimm** [comment]
@alsoicode Thank you so much! That works perfectly.

**Comment by alsoicode** [comment]
@Flimm You're welcome; very sorry that took so long to get done. Time has not been my friend this year.
