### ISSUE TITLE
Doc problem when extending custom templates

### ISSUE THREAD

**Issue by ricardorover** [alsoicode/django-admin-sortable#186]
Hi, found a doc issue.

When [extending custom templates](https://github.com/alsoicode/django-admin-sortable#extending-custom-templates) in django 2.0 (>= 1.6.x), documentation say to extend
`templates/adminsortable/edit_inline/tabular.html`

But after inspecting [the code](https://github.com/alsoicode/django-admin-sortable/blob/v2.1.3/adminsortable/admin.py#L315), I found out that it should be
`templates/adminsortable/edit_inline/tabular-1.10.x.html`
for all django versions >= 1.10

Hope this helps. Thanks and congrats for this project.

**Comment by alsoicode** [comment]
Sorry about that. I've updated the docs in the master branch.
