### ISSUE TITLE
Library does not work with django-parler

### ISSUE THREAD

**Issue by bmwant** [alsoicode/django-admin-sortable#190]
## Description
Cannot make it work when I have translatable admin and want to have sorted inline form for it.

## Example (how to reproduce)
```python
# models.py

class Item(TranslatableModel):
    name = models.CharField(max_length=100)  # this one is translatable
 
class Person(TranslatableModel):
    name = models.CharField(max_length=100)  # this one is translatable
    items = models.ManyToManyField(
        'Item',
        through='PersonItem',
    )


class PersonItem(Sortable):
   
    class Meta(Sortable.Meta):
        ordering = ['order']

    person = models.ForeignKey('Person')
    item = SortableForeignKey('Item')
```
```python
# admin.py

class PersonItemInline(TranslatableTabularInline, SortableTabularInline):
    model = PersonItem
    form = PersonItemForm
    extra = 1
```
**First case** when I inherit from translatable first I have no sorting feature.
**Second case** when I inherit from sortable first I get following error
```
NoReverseMatch
Reverse for 'person_person_do_sorting' with arguments '(239,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

How to make them work together?
`django==1.10.7`, `django-parler==1.6.5`, `django-admin-sortable==2.0.19`

**Comment by alsoicode** [comment]
I'm not familiar with django-parler, but I'll try to take a look and see what's going on.

**Comment by bmwant** [comment]
@alsoicode see also https://stackoverflow.com/questions/49858200/make-django-admin-sortable-and-django-parler-work-together in case you'll need more details

**Comment by bashu** [comment]
@bmwant ensure that the inhreritance order is correct:
```python
class PersonItemInline(SortableTabularInline, TranslatableTabularInline):
   ...
class PersonAdmin(SortableAdmin, TranslatableAdmin):
  ...
```

and override ``change_form_template_extends`` in ``PersonAdmin`` class like this:
```python
class PersonAdmin(SortableAdmin, TranslatableAdmin):
    change_form_template_extends = 'admin/parler/change_form.html'
```

**Comment by bmwant** [comment]
Ok, so I did manage to resolve this issue by properly specify inheritance order and also by merging `change_form` template both for `django-parler` and `django-admin-sortable`
