### ISSUE TITLE
Error when I try to sort objects with a filter applied in the get (admin)

### ISSUE THREAD

**Issue by StevenMedina** [alsoicode/django-admin-sortable#194]
![fielderror_at__admin_catalog_product_sort_](https://user-images.githubusercontent.com/9811859/41661570-a5f36930-7464-11e8-8afd-064d5013aa2a.png)

Hello, I just made a filter inside django's admin in an object that contains adminsortable, when I make the filter and I am ready to order those objects I get an error 500, could you help me with it please? Thank you

**Comment by alsoicode** [comment]
Can you show me your ModelAdmin class?

**Comment by StevenMedina** [comment]
Okay, look 👍 thanks
![models_py_ _frutapp-backend](https://user-images.githubusercontent.com/9811859/41665210-0f12c872-746d-11e8-81d3-9bbd23349f05.png)

**Comment by alsoicode** [comment]
This is your model. I need to see your admin model.

**Comment by StevenMedina** [comment]
Okay

![admin_py_ _frutapp-backend](https://user-images.githubusercontent.com/9811859/41665849-a24917c6-746e-11e8-961e-98daca23a16c.png)

**Comment by alsoicode** [comment]
Fields that you specify in the admin class for `list_filter` have to correspond to fields on the model, and there are a limited number of field types these can apply to. See: https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter for more information.

I added a list filter to the ProjectAdmin class in the sample project in the source code for django-admin-sortable and I'm not seeing the an error when sorting models with the filter applied in the querystring.

**Comment by alsoicode** [comment]
@StevenMedina is everything working as expected now for you?

**Comment by StevenMedina** [comment]
@alsoicode yes, perfect thanks!

**Comment by alsoicode** [comment]
Super. Glad you were able to get everything working!
