### ISSUE TITLE
Inline sorting stopped working on version 2.1.6 

### ISSUE THREAD

**Issue by EmilioK97** [alsoicode/django-admin-sortable#195]
I notice that the inline sorting seems broke in the 2.1.6 version.
The drag and drop just not triggers.

The 2.1.5 version works as spected.

I'm using Django==2.0.6.
2.1.5 works just fine for me, It's only to report it.

**Comment by alsoicode** [comment]
Let me see what might be going on. All my tests are passing. 2.1.6 just added the ability to do a custom JavaScript callback after sorting was completed, but didn't alter any of the Python code.

**Comment by alsoicode** [comment]
I am so sorry - I made a small mistake when specifying the include(s) for stacked/tabular inlines. I'll get a release out shortly.

**Comment by alsoicode** [comment]
Ok, 2.1.7 has been uploaded to PyPi and I've manually verified that inlines are sorting properly in the sample app. Please let me know if you still run into issues.
