### ISSUE TITLE
Performance is horrible when re-ordering a large number of objects.

### ISSUE THREAD

**Issue by mrmachine** [alsoicode/django-admin-sortable#197]
The current implementation simply iterates a list of model instances and calls `.save()` on every single one.

https://github.com/alsoicode/django-admin-sortable/blob/6d5f9e97b493a8d523e00a6076b3446dc0b8bbd5/adminsortable/admin.py#L298-L305

We've got an ordered model with ~3.5k objects and new objects get added to the end, but we often need to move them up near the top. That means calling `.save()` about ~3.5k times, often.

To make matters worse, we have some heavy caching of data that is derived from these objects. Every time one of these objects is saved, the cache gets invalidated.

This all adds up to being so slow that moving a single object from the end to near the beginning is exceeding the 50s timeout we have set on our reverse proxy.

I think it should be possible to do this much more efficiently with `F()`. Something like this (untested):

```python
original_order = obj.order  # e.g. 100
new_order = N  # e.g. 80
diff = new_order - original_order  # e.g. -20
order_field_name = Model.Meta.ordering[0].lstrip('-')
Model.objects \
.order_by(('-' if diff < 0 else '') + order_field_name) \  # e.g. -order
.filter(**{
    '%s__%s' % (order_field_name, 'lt' if diff < 0 else 'gt'): original_order,  # e.g. order__lt
}) \
[:abs(diff)] \  # e.g. 20
.update(**{
    order_field_name: F(order_field_name) + (1 if diff < 0 else -1),
})
obj.order = new_order
obj.save()
```

This should always result in no more than 2 queries to adjust the order, no matter the distance in between.

What do you think?

**Comment by alsoicode** [comment]
I always welcome pull requests. If you feel this approach will work, and it passes all the tests, I'm more than happy to adopt this methodology.

**Comment by mrmachine** [comment]
Thanks. I was just checking if you knew of any reasons why it wouldn't work before I go any further.

**Comment by alsoicode** [comment]
Any updates on your changes?
