### ISSUE TITLE
'get_django_version' received too many positional arguments

### ISSUE THREAD

**Issue by derek-adair** [alsoicode/django-admin-sortable#199]
I'm trying to upgrade from 2.1 to 2.1.7 and i'm getting the following template error

'get_django_version' received too many positional arguments

```
{% load i18n admin_urls admin_static admin_modify django_template_additions %}{% load cycle from future %}
{% get_django_version as django_version %}
<div class="inline-group {% if django_version.major >= 1 and django_version.minor >= 9 %}flat-admin{% endif %}" id="{{ inline_admin_formset.formset.prefix }}-group">

```

**Comment by derek-adair** [comment]
Hmmmmmmmmmmmmmm i'm stuck on 2.1.6 for some reason.

**Comment by alsoicode** [comment]
I'm not sure why that would be happening. That template tag doesn't accept any arguments: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/templatetags/django_template_additions.py#L79

**Comment by ryanbagwell** [comment]
Shouldn't this be:

```
{% with get_django_version as django_version %}
...
{% endwith %}
```

**Comment by alsoicode** [comment]
No, you can store the result of the tag in a template variable using "as". See the last section of: https://docs.djangoproject.com/en/2.1/howto/custom-template-tags/#simple-tags

**Comment by ryanbagwell** [comment]
Looks like that started in Django 1.9. I'm using 1.8, so I'm assuming that's my issue (FWIW the docs say the latest version is compatible with 1.8+)

**Comment by alsoicode** [comment]
AH, that could definitely be my fault :) Let me see if I can find a compatible version for you.

**Comment by alsoicode** [comment]
Could you please try version 2.0.21? I think that's probably the latest you can use with Django 1.8

**Comment by derek-adair** [comment]
I have 2.1.0 working w/ django 1.8.13.

**Comment by alsoicode** [comment]
Glad you got it working. Sorry for any time lost.

**Comment by derek-adair** [comment]
It actually was a bug not related to your code at all, so feel better XD

**Comment by alsoicode** [comment]
It can still be difficult to track down issues like that. I'm facing a similar situation with Keystone.js + Nunjucks and TypeScript :)

**Comment by ryanbagwell** [comment]
@alsoicode thanks, 2.0.21 worked with Django 1.8. Sorry for using an antiquity ...

**Comment by alsoicode** [comment]
No worries at all. It's funny how quickly something becomes in Internet years, especially in the land of JavaScript.
