### ISSUE TITLE
Missing buttons to change order in Django admin

### ISSUE THREAD

**Issue by dylanmccall** [alsoicode/django-admin-sortable#203]
Hiya! In the project readme, I see what looks like some accessible up and down buttons to change order [when sorting inlines](https://camo.githubusercontent.com/68914a2a4fc6276fbe77245174eb1b4ce541cd00/687474703a2f2f7265732e636c6f7564696e6172792e636f6d2f616c736f69636f64652f696d6167652f75706c6f61642f76313435313233373535352f646a616e676f2d61646d696e2d736f727461626c652f736f727461626c652d696e6c696e65732e6a7067). However, I'm not seeing those in my own project, using Django 1.11.x: https://github.com/dylanmccall/stuartmccall.ca/tree/master/galleries. Is there something in particular I'm missing, or is that screenshot out of date? :)

Here's what I'm seeing at the moment:

![screenshot from 2019-01-09 09-41-20](https://user-images.githubusercontent.com/132063/50918043-ffbbf700-13f3-11e9-9ddc-905a9634d17f.png)

**Comment by alsoicode** [comment]
Hi @dylanmccall I'll need to set up a project using 1.11.x and see what the problem might be. I'm out of pocket until the weekend on a business trip, but I'll try to take a look before then.

**Comment by dylanmccall** [comment]
Ah, poking at the source repo I see there's a separate template used for 1.10+ which doesn't include those arrows (seen here in a pre-1.10 template: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/edit_inline/tabular.html#L31). But looks like it's just an icon anyway. The visual discrepancy got my mind wandering :) I'd love some up and down sort buttons, so I'll see if I can implement those on my end. Hopefully I can do something reasonably general and send you a PR.

**Comment by alsoicode** [comment]
The 1.10.x templates are for that range specifically. After that, it should be using the `stacked.html` and `tabular.html` templates, which do include the FontAwesome sorting icons: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/edit_inline/stacked.html#L12

Which version of Django Admin Sortable are you using?

**Comment by alsoicode** [comment]
Closing this for now. You can re-open if necessary
