### ISSUE TITLE
Broken JS with custom CSRF_HEADER_NAME setting

### ISSUE THREAD

**Issue by ron8mcr** [alsoicode/django-admin-sortable#204]
There is fixed value of CSRF header name in [jquery.django-csrf.html](https://github.com/alsoicode/django-admin-sortable/blob/d4f577fdf905aa1cdef7fe2bce490197b68cbaa5/adminsortable/templates/adminsortable/csrf/jquery.django-csrf.html#L30). It may be set using Django setting [CSRF_HEADER_NAME](https://docs.djangoproject.com/en/2.1/ref/settings/#csrf-header-name), so this value should be passed from view to this template.

**Comment by alsoicode** [comment]
Hi @ron8mcr I have a branch to fix this ready to go, just need some time to get it deployed to PyPi for you.

**Comment by alsoicode** [comment]
Ok, 2.1.10 is available for you on PyPi.
