### ISSUE TITLE
CSRF Token missing or incorrect when sorting (POST Ajax)

### ISSUE THREAD

**Issue by tonykyriakidis** [alsoicode/django-admin-sortable#206]
Somehow I get a:
` Forbidden (CSRF token missing or incorrect.): /admin/amp_stories/story/sort/do-sorting/7/
`
in my settings I have:
` CSRF_COOKIE_HTTPONLY = False
`

my admin.py:

```python
from django.contrib import admin
from .models import Story, Page, Bookend, BookendSection
from adminsortable.admin import SortableAdmin, SortableTabularInline


class PagesInline(SortableTabularInline):
    model = Page


class BookendSectionInline(admin.TabularInline):
    model = BookendSection


class BookendAdmin(admin.ModelAdmin):
    inlines = [
        BookendSectionInline
    ]


class StoryAdmin(SortableAdmin):
    prepopulated_fields = {"slug": ("title",)}
    inlines = [
        PagesInline,
    ]


admin.site.register(Story, StoryAdmin)
admin.site.register(Bookend, BookendAdmin)
```

my models.py
```python
class Story(TimeStampedModel):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.title

class Page(TimeStampedModel, SortableMixin):
    """
    A page represent each "Slide" of a story. Currently you can upload JPEG and MP4 files.
    """

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'
        ordering = ['page_order']

    FILE_TYPES = (
        ("PHOTO", "PHOTO - JPEG"),
        ("VIDEO", "VIDEO - MP4"),
    )

    story = models.ForeignKey(Story, on_delete=models.CASCADE, null=True)
    title = models.CharField(blank=True, null=True, max_length=200)
    file_type = models.CharField(max_length=5, choices=FILE_TYPES)
    upload = models.FileField(upload_to=story_upload_path)

    def __str__(self):
        if self.title:
            return self.title
        else:
            return str(self.id)


    # define the field the model should be ordered by
    page_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

```

What could be the cause of this? I am using Django 2.1.4

**Comment by alsoicode** [comment]
Hi @tonykyriakidis. I'm not sure off the top of my head, but I can look into it for you.

**Comment by tonykyriakidis** [comment]
> Hi @tonykyriakidis. I'm not sure off the top of my head, but I can look into it for you.

that would be great! I still haven't found a way to fix it.

**Comment by alsoicode** [comment]
It may be tomorrow before I can look at it. I'm slammed on my current project and have a family event to attend this evening.

**Comment by alsoicode** [comment]
I think I may have accidentally broken the csrf functionality with a recent release, although all of my tests are passing. The default value of `CSRF_COOKIE_HTTPONLY` is already false, so I think it's another issue entirely.

**Comment by alsoicode** [comment]
For some reason, with 2.1.4, Django is expecting the `csrfmiddlewaretoken` value to be in the POST data and not just the request headers it seems. I have the changes in place and manual testing for regular models and inlines is working as expected now.

I should be able to get a new version out to PyPi for you within the hour.

**Comment by alsoicode** [comment]
Ok, 2.1.11 is available for you on PyPi. Please let me know if this works for you.

**Comment by tonykyriakidis** [comment]
Confirmed, it works! Thank you very much! Enjoy your evening!

**Comment by alsoicode** [comment]
You're very welcome.
