### ISSUE TITLE
Conflict with list_filter

### ISSUE THREAD

**Issue by makarqa** [alsoicode/django-admin-sortable#207]
Cached a conflict with list_filter when filtering by more than 1 param.
For example, with query
`/admin/catalog/product/?brand__id__exact=38&subcategory__id__exact=10`
I see all objects with _brand_id_, but not filtered by _subcategory_. So the only first query seems to be applied.

**Comment by alsoicode** [comment]
Hi @makarqa Help me understand the issue better. Are you saying that when looking at the Change List for your Catalog object and filtering by more than one criteria that you're not seeing the objects you're expecting? If so, I'm not sure how that relates to Django Admin Sortable, as this package doesn't make any modifications to the Change List view.

**Comment by makarqa** [comment]
Yes. When I apply filter, I can see objects which I was looking for (sorted by both criterias). But when I go to sorting mode there are objects, sorted only by first given criteria.

To help you understand, I've captured a video (it is on russian, but I think it will be ok to understand situation) https://drive.google.com/file/d/11tNUwzS9v5kmXhZewwt2dxAOSQvnELKq/view?usp=drivesdk . When I go to sorting mode (on the video it's on 0:19) there are more objects than in normal mode, because they are filtered only by 1 criteria.

Thank you and sorry for my english.

**Comment by alsoicode** [comment]
Gotcha. Let me look into it, and your English is great.

**Comment by alsoicode** [comment]
Ok, I have the root of the problem fixed, but I need to make some adjustments in the templates to properly handle the number of items available to sort.

**Comment by alsoicode** [comment]
@makarqa I've made the appropriate template updates and should be able to get a new version out to PyPi later today or tomorrow.

**Comment by alsoicode** [comment]
Had some extra time after all. Version 2.1.12 is available on PyPi for you.

**Comment by makarqa** [comment]
Thanks a lot! Will check it as soon as I can.

**Comment by makarqa** [comment]
Works fine now, thank you!

**Comment by alsoicode** [comment]
You're very welcome
