### ISSUE TITLE
FieldError: Cannot resolve keyword '_to_field' into field.

### ISSUE THREAD

**Issue by deluge** [alsoicode/django-admin-sortable#208]
With the latest version 2.1.12 there is a bug for admin inline "raw_id_fields". When I clicked the loupe and the popup is opening, I get this error. The bug seems to be here:
https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/admin.py#L47

```
    for k, v in request.GET.items():
        filters.update({ k: v })
```

**Comment by alsoicode** [comment]
@deluge Sorry about that. Can you please give the master branch a try? I've put in a fix and tested on my end that should work for raw_id fields.

**Comment by deluge** [comment]
Hey thanks for the fast feedback. I installed the master and all looks fine :) 

What about the next release? Will it be released soon?

**Comment by alsoicode** [comment]
You're welcome 2.1.13 is available for you on PyPi: https://pypi.org/project/django-admin-sortable/

**Comment by haakenlid** [comment]
Why is django-admin-sortable even parsing query parameters here? This happens when django-admin list view list-filter query parameters leaks into the ajax requests from django-admin-sortable. The ajax POST payload should be enough.
