### ISSUE TITLE
"Common Use Case": Categories order doesn't affect Projects

### ISSUE THREAD

**Issue by tonxxx** [alsoicode/django-admin-sortable#211]
Hi!

I'm using latest version with last Python and Django; tried locally and also at Digital Ocean.

These are the Models: https://github.com/alsoicode/django-admin-sortable#common-use-case

When I change an order of Projects inside any Category, everything works fine. When I change the Categories' order, it doesn't affect Projects:
![download](https://user-images.githubusercontent.com/23074442/53714678-e5494b80-3e81-11e9-8c79-c184c7571046.png)

I've also tried Projects/Categories from the sample_project with the same results.

**Comment by alsoicode** [comment]
The "Category" and "Project" models are separate. Changing the order of either of those models won't affect the other.

Project specifies Category as a SortableForeignKey field, allowing you to specify an order for the categories listed under a Project. Sorting the Category instances won't affect the order of projects or vice-versa.

If there is only one instance of a foreign key model, as in the "second cat #3" under "second", it isn't sortable, as there are no other model instances to order it relative to.

I also don't understand the data displayed in your screenshots. The image at left is displaying the Projects/Categories hierarchy when sorting, which makes sense.

The image at right appears to be the Projects change list, but the data appears to be for Category models.

All of the unit tests for ordering models in the sample project are passing. These test fire the same ajax calls that the browser does, check the subsequent ordering, etc, and everything is working as expected.

**Comment by tonxxx** [comment]
Thanks for fast reply! Let me explain what I'm trying to achieve:

1. I've created three Categories - first, second & third and some Projects related to these. This is how everything is sorted:
![screenshot_15](https://user-images.githubusercontent.com/23074442/53734410-7a663780-3eb6-11e9-87bd-a3c00e16c100.jpg)

2. Now I want to change the order of Categories and Projects, I pressed "CHANGE ORDER" at the Projects page and want to achieve the same order as at this image:
![image](https://user-images.githubusercontent.com/23074442/53734534-d466fd00-3eb6-11e9-8e77-709c1e9493b2.png)

3. After I rearranged everything, I expect the Projects to be sorted exactly as at the previous image. But this is the actual order (red lines just separate the Projects of different Categories)
![image](https://user-images.githubusercontent.com/23074442/53734646-2c9dff00-3eb7-11e9-9ee9-40e2e82579c4.png)

I was expecting the Projects to be arranged according to the Categories order. Makes sense to me, especially because the hierarchy at second image was achieved from Projects page anyway =) In my actual use case, the Projects list is rather a long one, so I order the Projects belonging to most popular Categories first.

**Comment by alsoicode** [comment]
You're going to need to show me your models, because your screen shots aren't lining up with your description of the data.

If I understand you correctly, your "Project" model is specified as a SortableForeignKey on Category?

Sorting the Projects is in no way going to affect the sort order of the parent Category, as the sort order of Projects is unique per Category instance, if indeed Project is a foreign key.

**Comment by tonxxx** [comment]
I took the models from here:
https://github.com/alsoicode/django-admin-sortable#common-use-case

Project.category = SortableForeignKey(Category)

Let's say I have the following structure:
Category A
--Project 1
--Project 2
Category B
--Project 3
--Project 4
The initial order is "Category A > Category B", so the Projects are sorted this way:
--Project 1
--Project 2
--Project 3
--Project 4

When I change the Categories order from "A to B" to "B to A" the Projects order remains the same although I expect it to change this way:
--Project 3
--Project 4
--Project 1
--Project 2

**Comment by alsoicode** [comment]
No, that's not how it works :)

When you're talking about a foreign key model, the order is relative to the parent, not to Projects *overall*

The Projects for Category A are ordered relative to Category A.
The Projects for Category B are ordered relative to Category B.

**Comment by tonxxx** [comment]
OK thanks, it's a pity =)

**Comment by alsoicode** [comment]
Well, I don't really see it as a pity, as the behavior is simply following the relational model.

You could still get the ordering you're looking for by creating your own list, first iterating over the Category instances, and then their respective Projects.

**Comment by tonxxx** [comment]
Sure, thanks. Actually, it's not a problem for me. Thanks for a great package! 👍

**Comment by alsoicode** [comment]
You're very welcome,
