### ISSUE TITLE
Dragging changes FontAwesome icons that it shouldn't

### ISSUE THREAD

**Issue by whatisjasongoldstein** [alsoicode/django-admin-sortable#215]
We use FontAwesome icons in some custom widgets in the Django Inlines.

When dragging inlines, all the icons turn into `fa-sort`.

This is because this selector is too broad:

https://github.com/alsoicode/django-admin-sortable/blob/ff4dc3184f131863b270b8e7e0d4e4f0fb0db936/adminsortable/templates/adminsortable/edit_inline/admin.sortable.tabular.inlines.html#L43

That will catch _any_ fontawesome class, including ones that Django-Admin-Sortable shouldn't touch.

I'd be happy to make the PR but I don't know what the selector _should_ be (or where the icon normally appears, since I don't have one on my admin).

![Kapture 2019-08-26 at 15 03 41](https://user-images.githubusercontent.com/377630/63715898-c0230d80-c812-11e9-9c2d-1204587ad3cd.gif)

**Comment by alsoicode** [comment]
Ok, version 2.1.18 is available for you on PyPi.

**Comment by whatisjasongoldstein** [comment]
Awesome. Thanks again!
