### ISSUE TITLE
`staticfiles` and `adminstatic` template tag libraries have been deprecated and removed

### ISSUE THREAD

**Issue by cjtapper** [alsoicode/django-admin-sortable#217]
`{% load staticfiles %}` and `{% load adminstatic %}` were [deprecated in Django 2.1](https://docs.djangoproject.com/en/2.2/releases/2.1/#features-deprecated-in-2-1), and [removed in Django 3.0](https://docs.djangoproject.com/en/dev/releases/3.0/#features-removed-in-3-0).

There are a couple of occurrences that I can see:

https://github.com/alsoicode/django-admin-sortable/blob/612de9ea9d3fa68c34bb3479c2f83f2f10ebf05f/adminsortable/templates/adminsortable/edit_inline/stacked.html#L1

https://github.com/alsoicode/django-admin-sortable/blob/5cb0f1ebf8d8abb75782e3c4a86cd1b582450f59/adminsortable/templates/adminsortable/edit_inline/tabular.html#L1

https://github.com/alsoicode/django-admin-sortable/blob/5cb0f1ebf8d8abb75782e3c4a86cd1b582450f59/adminsortable/templates/adminsortable/change_form.html#L3

I'll submit a pull request for this, but I'm not entirely clear on what will need to be done here for backwards compatibility.

**Comment by alsoicode** [comment]
It's been a while since I've looked at a conditional load statement, but it's probably easiest just to introduce a new breaking version of adminsortable for Django 3 at 2.2 and not try to make it backwards compatible.

There are some other bits of legacy code that can be removed for much older versions of Django in there as well, and this version would be a good time to remove those.

**Comment by cjtapper** [comment]
> There are some other bits of legacy code that can be removed for much older versions of Django in there as well, and this version would be a good time to remove those.

I'm happy to take a look at these, too, if you happen to know where in the repo I should be looking.

**Comment by alsoicode** [comment]
Most of that code would be in the admin.py file, for instance here: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/admin.py#L187

**Comment by alsoicode** [comment]
Version 2.2.0 has been released to PyPi which is working with Django 3 according to my unit and hand-testing. Please let me know if you run into any issues.
