### ISSUE TITLE
Deleting from a SortableTabularInline class does not update the order of all elements in the list

### ISSUE THREAD

**Issue by ColbyPowers** [alsoicode/django-admin-sortable#219]
I am using version 2.1.16.

When I delete an item from an inline inheriting from the SortableTabularInline, the order of the other elements is not updated to reflect the changes from the delete. For example, I have a list of fruits: 

1) Apple
2) Banana
3) Orange

If I delete "Banana", Orange's order stays at 3. The only way to reset the order, is to use the drag and drop after I delete the "Banana" object.

**Comment by alsoicode** [comment]
This isn't a bug, it's just the way admin sortable works. When considering sort order, the number of the next object is irrelevant programmatically. When you add another object, it's going to get whatever the max or min value is depending on your sort order and add or subtract 1 to the value.

What the number used for the order value actually is doesn't matter (to admin sortable's programming) as long as the numbers increase or decrease in value and don't overlap.

So, the bottom line is, don't count on the order to be sequential.
