### ISSUE TITLE
No tests run with django 3.0

### ISSUE THREAD

**Issue by Mogost** [alsoicode/django-admin-sortable#220]
In my opinion, we need to revise the supported versions of python and django. Drop djnago/python support that is in end of life stage.
Also need to improve classfiers in setup.py.

**Comment by alsoicode** [comment]
Pull requests are always welcome

**Comment by alsoicode** [comment]
@Mogost I am able to run all tests with Python 3.6.5 and Django 3

<img width="505" alt="admin-sortable-django3-tests" src="https://user-images.githubusercontent.com/86738/71485957-cbe30880-27e1-11ea-95c7-1b2020aaa420.png">

**Comment by Mogost** [comment]
I mean that in CI (Travis) there is no Django 3.0 env.

чт, 26 дек. 2019 г., 21:15 Brandon Taylor <notifications@github.com>:

**Comment by alsoicode** [comment]
Fixed
