### ISSUE TITLE
Header row for SortableTabularInline is draggable in admin form

### ISSUE THREAD

**Issue by sseveringhaus-newclassrooms** [alsoicode/django-admin-sortable#221]
Hi there. I'm using version 2.1.18 and Django 2.2.7. I've got a `SortableTabularInline` underneath a `NonSortableParentAdmin` for a model. Drag-and-drop works fine, except that the header row is also draggable. Dropping the header row causes a 500 error, though I won't clutter this report with the stack trace, since I think it's not relevant. (It's trying to post data that it shouldn't be trying to post in the first place.)

Is this a known issue? The only other oddity I'm seeing is that the up/down draggability icons shown in the README's screenshots don't appear.

As a side note, the README [states](https://github.com/alsoicode/django-admin-sortable/blame/master/README.md#L24), `For Django 1.8.x < 3.0, use 2.1.8.`, but for what it's worth, 2.2 seems to work more or less fine with Django 2.2.7, albeit with this same issue that I'm reporting.

Thank you for the great module!

**Comment by alsoicode** [comment]
Hi @sseveringhaus-newclassrooms this error is being caused by the selector for the tabular inline group here: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/templates/adminsortable/edit_inline/admin.sortable.tabular.inlines.html#L13 and it's affecting all versions. I'm surprised (and embarrassed) that no one has caught this in the past 9 years (facepalm)

The fix is super simple, so I'll get a new version out this evening. I'll need to also figure out a way to provide a patch for older versions as well.

**Comment by alsoicode** [comment]
2.2.1 is available for you on PyPi: https://pypi.org/project/django-admin-sortable/

Please let me know if you're still having issues.

**Comment by sseveringhaus-newclassrooms** [comment]
Thank you, sir. Works like a charm with Django 2.2.7. I'm not readily able to test with newer versions, but I can give it a try if it would be helpful.

**Comment by alsoicode** [comment]
You're very welcome, and thanks for the coffee! I also looked into the problem with the FontAwesome icons not showing up in the inline sortable models. That's been fixed as well and is now available on PyPi as version 2.2.2 if you want to update your requirements.txt

**Comment by sseveringhaus-newclassrooms** [comment]
Hm. This gives me a `TemplateSyntaxError` `'future' is not a registered tag library`. Some quick searching suggests that `cycle` has [been removed](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-1-10) from `future`, but possibly I'm doing something else wrong here.

**Comment by alsoicode** [comment]
It's probably my fault. The inline template overrides are complicated. 2.2.2 is working as expected with Django 3, but I may need to make some adjustments for backwards compatibility.

**Comment by alsoicode** [comment]
OK, sorry about that. I had loaded the wrong inline templates for Django 2 or higher. Version 2.2.3 is working for me with Django 2 & 3 and is available on PyPi.
