### ISSUE TITLE
Dragging works weird when there is only one child

### ISSUE THREAD

**Issue by andreymal** [alsoicode/django-admin-sortable#234]
I make classic Category→Post hierarchy with Django 3.0 and django-admin-sortable 2.2.3, but when I'm trying to drag categories with one child, it looks weird and is not working.

It seems the "black" children should ignore dragging, but they don't ignore it.

![](https://i.imgur.com/avsm8db.gif)

**Comment by alsoicode** [comment]
Hi @andreymal . I'm having some trouble replicating this behavior. Can you please send me your models / admin classes?

**Comment by andreymal** [comment]
@alsoicode nothing special, just a regular parent-child structure. Reproducible on an empty django project

![](https://i.imgur.com/Rqd2CJo.png)
