### ISSUE TITLE
Sorting cache issue

### ISSUE THREAD

**Issue by calliday** [alsoicode/django-admin-sortable#235]
As an example, my project has Recipes and Ingredients, with RecipeIngredients doing the many-to-many mapping between the two from Recipe.

I have added the tabular inline many-to-many sorting functionality referenced in the Readme, and it works great until I use the 'back' button.

If I reorder the ingredients on a recipe, save, then move back to the recipe via the 'back' button, the ingredients are in the appropriate (new) order, yet the columns that use a drop-down select box have the old ordering, showing reference to the wrong ingredient.

At that point, if I refresh, they go back to normal, but if I begin making edits, a second save overwrites the ingredients with the wrong values.

**Update:** This has only been happening with Chrome and drop-down boxes within the tabular inline, it doesn't happen with Safari. Is this an issue with Chrome's cache or admin-sortable's method of updating the data when dragging and dropping? I will be testing it out in Firefox today.

**Comment by alsoicode** [comment]
Hi @calliday. Sorry for the slow reply, It's been a rough week. django-admin-sortable should be firing a POST request when the item is dropped, so even if you don't save the model, the order should be preserved.

django-admin-sortable doesn't officially support sorting on many-to-many relationships, so I'm not sure what exactly might be going on. If you can share your models/admin models with me, I can try to see what's going on.
