### ISSUE TITLE
README.md saying to use version 2.1.8

### ISSUE THREAD

**Issue by adi1** [alsoicode/django-admin-sortable#236]
In the README.md, it says:

For Django 1.8.x < 3.0, use 2.1.8.

Is this supposed to say 2.1.18?

**Comment by adi1** [comment]
Sorry, I made a mistake, there are no missing js files in 2.1.8. The question still stands though, should we be using 2.1.18 or 2.1.8 as mentioned in the README?

**Comment by alsoicode** [comment]
For Python less than version 3, you should be safe with 2.1.9
