### ISSUE TITLE
Wheel for Python 3

### ISSUE THREAD

**Issue by michael-k** [alsoicode/django-admin-sortable#237]
I've noticed that for versions [2.2](https://pypi.org/project/django-admin-sortable/2.2/#files) and [2.2.1](https://pypi.org/project/django-admin-sortable/2.2.1/#files) there's a wheel for Python 3 but not for Python 2 on PyPI.  And  for versions [2.2.2](https://pypi.org/project/django-admin-sortable/2.2.2/#files) and [2.2.3](https://pypi.org/project/django-admin-sortable/2.2.3/#files) it's the other way round (wheel for Python 2, but not for Python 3).

Would it be possible to provide a Python 3 wheel for all future versions and maybe also for 2.2.3?

According to the [readme](https://github.com/alsoicode/django-admin-sortable#supported-django-versions) v2.2.* only supports Django 3 which in turn only supports Python 3.  Therefore wheels for Python 2 shouldn't be necessary any more.

**Comment by alsoicode** [comment]
First, my most sincere apologies for the inexcusable delay in responding to your request. Due to work and other extenuating circumstances, I have been unable to contribute to this project for a very long time.

I have pushed wheels for all of the 2.x versions out to PyPi, including 2.2.3 and 2.2.4.
