### ISSUE TITLE
Creating object with always overrides sorted field value

### ISSUE THREAD

**Issue by bmihelac** [alsoicode/django-admin-sortable#240]
Hello everyone!

As the title says creating object always overrides sorted field value with current_max+1 (relevant code: https://github.com/alsoicode/django-admin-sortable/blob/master/adminsortable/models.py#L91-L99). 

While this is expected for object created through the admin interface it can be unexpected and undesired when creating object outside of the admin. Use case is for example, when list of ordered records already exists and new records should be inserted somewhere between them. 

Alternative could possible be to update sorted field value only current value is `None`. I am not sure if this change can lead to some breaking changes. Maybe something like this could work:

```python
the_order = models.PositiveIntegerField(blank=True, editable=False, db_index=True, unique=True)
```

As a workaround, one option is to bulk create objects which does not result in calling `save` method.

**Comment by alsoicode** [comment]
Your model should inherit the `SortableMixin` class to ensure new instances that are created get their `order` field incremented. That functionality doesn't only apply to Django Admin.

**Comment by bmihelac** [comment]
@alsoicode thanks for quick answer - I am not sure if my report was understandable enough. 
The problem, in my opinion is that value of sort order field is overwritten on object create. For example if we use example model from the README:

```
MySortableClass.objects.create(title="foo", the_order=100)
```

Running this code would create record and override `the_order` value. This could be undesirable if one want to insert record somewhere between.

**Comment by alsoicode** [comment]
@bmihelac pull requests are always welcome if you want to come up with a strategy to handle this use case.

**Comment by bmihelac** [comment]
@alsoicode good, I'll prepare pull request soon
