### ISSUE TITLE
Seperate ordering in ChangeList view

### ISSUE THREAD

**Issue by nishanthvijayan** [alsoicode/django-admin-sortable#241]
I have a model with `id` and `rank` attributes among others. `rank` is the column I'm using in Model.Meta.Ordering option for django-admin-sortable`.

I want the change_list view to list items ordered by `id` DESC by default. However, because I set `rank` as the ordering key, the items appear sorted by `rank` by default. Is there any way I can override this behaviour? 

I tried keeping `ordering` in Model meta option as `rank` but `ordering` option of the ModelAdmin class as `-id`. This makes the items in change_list appear sorted by id but messes with the Change Order page items.

**Comment by alsoicode** [comment]
My suggestion would be to do a custom change_list.
