### ISSUE TITLE
Sample Project Not Working!

### ISSUE THREAD

**Issue by shahabsherveh** [alsoicode/django-admin-sortable#243]
When I try to change the "Credit" ordering of a "project" my browser prompts me the following error:

There are unsaved changes on this page. Please save your changes before reordering.

How can I solve this?

**Comment by shahabsherveh** [comment]
No empty inline should exist. This solved my problem

**Comment by ruohola** [comment]
Wondering why it even creates the empty inline there...

**Comment by jej** [comment]
For people having this problem, you can solve it by adding `extra = 0` in your admin class:

```
class MyListInline(SortableTabularInline):
    model = MyModel
    extra = 0 # no empty new line
```

Maybe the doc should specify this?

Hope it helps,
J.
