### ISSUE TITLE
Integrity Error, violates check constraint

### ISSUE THREAD

**Issue by cchacholiades** [alsoicode/django-admin-sortable#246]
Hi @alsoicode, I have been using this package and so far I had no issues, fantastic stuff! 🙌 

Some of the latest models I added throw an integrity error when I rearrange their items. I am having trouble getting past this issue..

Main difference I can think of is that these models have OneToOneFields but I don't know if that's related. 

```
IntegrityError at /admin/path/path/sort/do-sorting/178/
new row for relation "related_model" violates check constraint "related_model_inapp_display_order_check"
DETAIL:  Failing row contains (2, some text, t, -1).
```

```
django-admin-sortable==2.2.4
```

Any ideas/help? Thank you in advance.

**Comment by felipe3dfx** [comment]
Ensuring order doesn't have the minus sing

```python
# dont work
ordering = ['-order']  

# works
ordering = ['order']  
```

Good luck!

**Comment by cchacholiades** [comment]
wow 🤯 @felipe3dfx thank you.

**Comment by alsoicode** [comment]
@cchacholiades Sorry I wasn't able to get to you sooner. Thank you @felipe3dfx for helping out.
